/**
 * dfs-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2022-03-11T17:38:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { YtdStockdataResponseModelBodyItem } from './YtdStockdataResponseModelBodyItem';
import { HttpFile } from '../http/http';

export class YtdStockdataResponseModelBody {
    'item'?: YtdStockdataResponseModelBodyItem;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "item",
            "baseName": "item",
            "type": "YtdStockdataResponseModelBodyItem",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return YtdStockdataResponseModelBody.attributeTypeMap;
    }

    public constructor() {
    }
}

